# Generated by Django 4.1.1 on 2022-09-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emial',
            field=models.CharField(default='none@mail.com', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=24),
        ),
    ]
