# Generated by Django 4.1.1 on 2022-09-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_emial_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Xd', max_length=24),
        ),
    ]
